-- Insert into EMPLOYEE table (hashed password)
--INSERT INTO "EMPLOYEE" ("EMPLOYEE_ID", "EMPLOYEE_NAME", "PASSWORD") 
--VALUES (1, 'paul', '$2a$12$ZcOjJng3u9eTu6grfPFvA.2C5FjTAaKqwO.45FTnv.rUpaBcOlmum');

-- Insert into EMPLOYEE_ROLES table
--INSERT INTO "EMPLOYEE_ROLES" ("EMPLOYEE_ID", "ROLE") VALUES (1, 'TELLER');
--INSERT INTO "EMPLOYEE_ROLES" ("EMPLOYEE_ID", "ROLE") VALUES (1, 'MANAGER');

-- Insert into MANAGER table
--INSERT INTO "MANAGER" ("EMPLOYEE_ID") VALUES (1);